### ISSUE TITLE
Gateway is not supported

### ISSUE THREAD

**Issue by Monotek18** [OperationNT414C/CtrBootManager#3]
Since the A9LH v2, the Gateway arm9loaderhax is not longer supported.
Is there a way to fix that ?
Because bootctr9 support the Gateway bin file with the A9LH v2

**Comment by OperationNT414C** [comment]
Hello Monotek18,

I already had a report about unsupported Gateway arm9loaderhax but without any more precision. Is it when CtrBootManager9 tries to boot "arm9loaderhax.bin" from Gateway or is it when "arm9loaderhax.bin" from Gateway boots CtrBootManager9?

If you tell me the issue is since V2 version, it should be due to screeninit feature. The following version disables screen init:
[CtrBootManager9_2.0.0_NoScreenInit.zip](https://github.com/OperationNT414C/CtrBootManager/files/322293/CtrBootManager9_2.0.0_NoScreenInit.zip)
I don't have Gateway and I don't wish to install this team code on my 3DS (due to some brick rumors). Can you please try this version and report me if it works ?

Thank you for your help !

**Comment by Monotek18** [comment]
Ok thanks I'll try it tomorrow
I have tried with no "noscreeninit" and with the "screeninit", but same result.
And it's when CtrBootManager9 try to boot the Gateway "arm9loaderhax.bin"

PS: It will not brick your 3ds if you don't use the DSTWO+ (gateway clone) with the Gateway Launcher.dat ;)

**Comment by JustForNothing** [comment]
I say it also here: "CtrBootManager9_2.0.0_NoScreenInit.zip" doesn't work with Gateway
PS: Only bootctr9 can boot it, I don't know why

**Comment by OperationNT414C** [comment]
Ok, thank you for your test, just to be sure, here is the first unofficial CtrBootManager V1:
[CtrBootManager9_V1src_AlphaHighlight.zip](https://github.com/OperationNT414C/CtrBootManager/files/322410/CtrBootManager9_V1src_AlphaHighlight.zip)

Can you report if this first version works? (it was very sensitive if there was no configuration file)

When you say only BootCtr9 can boot it, did you also try BootAnim9 or Luma3DS (with Gateway "arm9loaderhax.bin" as a payload inside "/luma/payloads/start_Gateway.bin")?

**Comment by JustForNothing** [comment]
No it doesn't work too.
With bootctr9, I have Gateway.bin in "/luma/payloads/Gateway.bin"
I have this payload in default

**Comment by OperationNT414C** [comment]
Today, I just try to boot Gateway "arm9loaderhax.bin" given on this topic:
https://gbatemp.net/threads/tutorial-using-luma3ds-with-gateway-on-v2-a9lh.431691/

But when I try to start it with Luma3DS, it simply shutdown my 3DS (no crash, just a power off). I have the exact same behavior with CtrBootManager9 so I would say there is no error in CtrBootManager binary load :-). However, if I truly wish to start Gateway, I think I don't have a valid "Launcher.dat". Where could I find it?
I also tried the one given in "http://www.gateway-3ds.com/" for non-GW users, this one crashes when it is loaded as a Luma3DS payload (of course, same behavior with CtrBootManager9).

**Comment by JustForNothing** [comment]
I have tried this arm9loaderhax.bin, but it work as an "arm9loaderhax.bin", but not with ctrbootmanager9
You can find the Launcher.dat here
http://www.gateway-3ds.com/downloads/

And yes it give me black screen in all the way.
But only bootctr9 can boot it :(

**Comment by Monotek18** [comment]
problem fixed

**Comment by OperationNT414C** [comment]
Hello Monotek18,
Can you be more specific about this "problem fixed"? I didn't change anything in CtrBootManager for Gateway so I would like to have your experience for other users (maybe Gateway version to use).
Thank you for your help!

**Comment by Monotek18** [comment]
Well, just a stupid error 
Before I tried offset=12000 with the official Gateway arm9loaderhax.bin
And I didn't change it.
I change it to offset =0 with the unofficial Gateway arm9loaderhax.bin, and it worked
haha, what a stupid mistake

**Comment by OperationNT414C** [comment]
Ok, thank you for this report.
By "unofficial", do you mean this one?
https://gbatemp.net/threads/tutorial-using-luma3ds-with-gateway-on-v2-a9lh.431691/
If it is this one, did you use the "Gateway Logo" or "No Gateway Logo" version?

**Comment by Monotek18** [comment]
Yes it's this one, with the Gateway logo.

(PS: It's possible to add a function to change the brightness when I boot with ctrbootmanager9 ?)

**Comment by OperationNT414C** [comment]
Thank you for your clarification.
I will try to add a brightness setting feature when I have some time (already have the screen init code so it won't be very hard to add brightness). I am thinking about something like this in the config file to setup it:

```
[general]
brightness=3;
```

**Comment by Monotek18** [comment]
Well thanks again

Anyway I think this issue can now be closed :)
