### ISSUE TITLE
Super Smash dont start with CtrBoot

### ISSUE THREAD

**Issue by acelerador25** [OperationNT414C/CtrBootManager#8]
When I use this in direct start I try to open the game and don't start the game (and the 3ds led) but after returning the luma boot to the sd the game open and don't freezes the 3ds. Why it happens? This is a problem of the game or is from the boot? i don't have that problem when I have MenuHax in the past

**Comment by OperationNT414C** [comment]
I already have Super Smash Bros 3DS (EU) installed on my 3DS so I attempted the following scenario:
- Put Luma3DS.firm at the root of my SD card
- Put CtrBootManager9.firm (v2.4.0) renamed as "boot.firm" at the root of my SD card
- Power off my 3DS then start it

It directly boots CtrBootManager9 so I used it to start Luma3DS.firm: the CFW starts well. Then I launched Super Smash Bros: no problem.

**Comment by acelerador25** [comment]
I do that action and I have the same problem on that game only. That game can't start and I need to power off my 3ds because it freezes

**Comment by OperationNT414C** [comment]
Sorry but I can't reproduce this issue. If you directly start Luma3DS, you don't have any issue? Can you attach me your "a9lh.cfg" file?

**Comment by acelerador25** [comment]
I don't have that issue when I only with the luma.firm., is only when the Crtboot.firm is active in the 3ds
[a9lh.zip](https://github.com/OperationNT414C/CtrBootManager/files/1026459/a9lh.zip)

**Comment by OperationNT414C** [comment]
Add "/" at the begin of all your pathes:
path=Luma3ds.firm; => path=/Luma3ds.firm;
path=luma/payloads/Decrypt9WIP.firm; => path=/luma/payloads/Decrypt9WIP.firm;
Luma3DS is very sensitive to its start path, check the character case (upper or lower) of "Luma3DS.firm".

**Comment by acelerador25** [comment]
Thanks to that, this can open the game, now is time for play

**Comment by OperationNT414C** [comment]
You welcome, have fun!
